spring:

  datasource:
    url: jdbc:mysql://localhost:3306/hello_world?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    password: password
    username: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    basic:
      enabled: false
    user:
      name: user
      password: user

  management:
    security:
      enabled: false

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
#    suffix: .html


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB